pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'devops:latest'
  # imageName: 'devops:$(Build.BuildId)'

steps:
- script: dotnet restore
  displayName: 'Restoring Packages'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Building Project'

- task: DotNetCoreCLI@2
  displayName: 'Testing'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- script: |
    docker build --no-cache -f Dockerfile -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName)
  displayName: 'Pushing Image'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet publish $(buildConfiguration)'
#   inputs:
#     command: publish
#     publishWebProjects: True
#     arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#     zipAfterPublish: True

# - task: PublishBuildArtifacts@1
#   displayName: 'publish artifacts'